spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: springboot-3-3-9-jdk17-template
server:
  port: 8455
  shutdown: graceful
management:
  endpoint:
    refresh:
      enabled: true
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"